# Image-scan workflow is designed to scan the Docker images for vulnerabilities using Trivy. It is triggered on every push to the repository and can also be manually triggered using workflow_dispatch. The workflow runs on an Ubuntu environment and consists of steps to check out the code, set up Docker, install Trivy, and run the image scan to identify any known vulnerabilities in the Docker images used in the project.
# Trivy image scanner for CVE ->  DOcker images 
# Trivy Rating is like this -> 0 vulnerabilities found, 1 low, 2 medium, 3 high -> solution can be found , 4 critical -> 
name: Image Scan

on:
  workflow_call:

jobs:
  image-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Dockerfile (Hadolint)
        continue-on-error: true
        run: |
          if [ -f "Dockerfile" ]; then
            docker run --rm -i hadolint/hadolint < Dockerfile
          else
            echo "Dockerfile not found" && exit 1
          fi

      - name: Build local image for scanning
        # We build the image locally first so Trivy can scan the layers
        run: |
          docker build -t my-app-image:${{ github.sha }} .

      - name: Run Trivy Scanner
        uses: aquasecurity/trivy-action@v0.36.0 # Updated to a safe version
        with:
          scan-type: 'image'
          image-ref: 'my-app-image:${{ github.sha }}'
          severity: 'CRITICAL,HIGH'
          exit-code: '1' # This will fail the pipeline if vulnerabilities are found
          format: 'table'

      - name: Login to Docker Hub
        # Only login and push IF the scan passed
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}