# name: Portfoloi

# on:
#   workflow_dispatch: # This allows you to manually trigger the workflow from the GitHub Actions tab in your repository. It provides flexibility to deploy your portfolio whenever you want, without needing to push changes to the main branch.   
#  # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
# permissions:
#     contents: read      # to read the repository content and code
#     pages: write      # to deploy to Pages
#     id-token: write   # to verify the deployment originates from an appropriate source
# jobs:
#     deploy:
#         runs-on: ubuntu-latest
        
#         environment:
#             name: github-pages
#             url: ${{ steps.deployment.outputs.page_url }} # <-- This line uses the output from the deployment step to set the URL of the deployed site in the environment.



#         steps:
#             # This will give access to your portfolio repository content and code to the workflow
#             # clone the samw repo or checkout the code where the workflow is running/ written
#             - name: Checkout code
#               uses: actions/checkout@v4 # This action checks out your repository code by a pre-defined version so that the workflow can access it.
            
#             - name: configure to Github Pages
#               uses: actions/configure-pages@v4 # This action is used to deploy your portfolio to GitHub Pages. It will take care of building and deploying your site.
            
#             # Static code artifacts are generated by the build process and are stored in the 'build' directory. This step will upload those artifacts to GitHub Pages.
#             - name: Upload static  artifact
#               uses: actions/upload-pages-artifact@v4 # This action uploads the static code artifacts to GitHub Pages. # A composite action that uploads the static code artifacts generated by the build process to GitHub Pages. It ensures that the necessary files are available for deployment.
#               with:
#                 path: "." # This specifies the path to the static code artifacts that need to be uploaded. In this case, it is set to the current directory (".") which means all files in the repository will be included in the upload. You can adjust this path if your build process generates artifacts in a specific directory.

#             - name: Deploy to GitHub Pages
#               id: deployment
#               uses: actions/deploy-pages@v4 # This action deploys the uploaded static code
