# Sometimes we accidentally include API keys, tokens, passwords, etc., in our code. If pushed to GitHub, these secrets become public and can be misused. To prevent this, we use a secret scan workflow that scans our code for secrets. If any are found, the workflow fails, allowing us to remove them before pushing.
# We scan using Gitleaks, an open-source tool that scans code for secrets. If it finds any, it fails the workflow, so we can remove the secrets before pushing to GitHub.

name: secret scan

     
on:
     workflow_call:


jobs:
        secret-scan:
            runs-on: ubuntu-latest
            steps:
                - name: checkout code
                  uses: actions/checkout@v4
                  with:
                    fetch-depth: 0 # This line ensures that the entire commit history is fetched when checking out the code. This is important for secret scanning tools like gitleaks, which may need access to the full commit history to effectively scan for secrets that may have been introduced in previous commits.

                - name: install gitleaks scanner
                  uses: gitleaks/gitleaks-action@v2
                  env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This line sets the GITHUB_TOKEN environment variable with the value of the GITHUB_TOKEN secret. The GITHUB_TOKEN is a special token provided by GitHub Actions that allows the workflow to authenticate with the GitHub API. It is used by the gitleaks-action to access the repository and perform secret scanning.

                
