# sometime we API keys, tokens, password etc in our code by mistake and if we push that code to github then that secret will be public and anyone can use that secret for malicious purpose. So to avoid that we can use secret scan workflow which will scan our code for any secrets and if it find any secret then it will fail the workflow and we can remove that secret from our code before pushing it to github.
# we will scan it by gitlealks -> gitleaks is a open source tool which is used to scan our code for any secrets. It will scan our code and if it find any secret then it will fail the workflow and we can remove that secret from our code before pushing it to github.

name: secret scan

     
on:
     workflow_call:


jobs:
        secret-scan:
            runs-on: ubuntu-latest
            steps:
                - name: checkout code
                  uses: actions/checkout@v4
                  with:
                    fetch-depth: 0 # This line ensures that the entire commit history is fetched when checking out the code. This is important for secret scanning tools like gitleaks, which may need access to the full commit history to effectively scan for secrets that may have been introduced in previous commits.

                - name: install gitleaks scanner
                  uses: gitleaks/gitleaks-action@v2
                  env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This line sets the GITHUB_TOKEN environment variable with the value of the GITHUB_TOKEN secret. The GITHUB_TOKEN is a special token provided by GitHub Actions that allows the workflow to authenticate with the GitHub API. It is used by the gitleaks-action to access the repository and perform secret scanning.

                
